/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminConversoesRouteImport } from './routes/admin/conversoes'
import { Route as AdminConteudoRouteImport } from './routes/admin/conteudo'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminAgendamentosRouteImport } from './routes/admin/agendamentos'

const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversoesRoute = AdminConversoesRouteImport.update({
  id: '/conversoes',
  path: '/conversoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendamentosRoute = AdminAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/conversoes': typeof AdminConversoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leads': typeof AdminLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/conversoes': typeof AdminConversoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leads': typeof AdminLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/conversoes': typeof AdminConversoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leads': typeof AdminLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendar'
    | '/admin/agendamentos'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/conversoes'
    | '/admin/dashboard'
    | '/admin/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agendar'
    | '/admin/agendamentos'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/conversoes'
    | '/admin/dashboard'
    | '/admin/leads'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendar'
    | '/admin/agendamentos'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/conversoes'
    | '/admin/dashboard'
    | '/admin/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendarRoute: typeof AgendarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversoes': {
      id: '/admin/conversoes'
      path: '/conversoes'
      fullPath: '/admin/conversoes'
      preLoaderRoute: typeof AdminConversoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agendamentos': {
      id: '/admin/agendamentos'
      path: '/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AdminAgendamentosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendamentosRoute: typeof AdminAgendamentosRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminConversoesRoute: typeof AdminConversoesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendamentosRoute: AdminAgendamentosRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminConteudoRoute: AdminConteudoRoute,
  AdminConversoesRoute: AdminConversoesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLeadsRoute: AdminLeadsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendarRoute: AgendarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
